version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_PASSWORD: 123qwe
      MYSQL_ROOT_PASSWORD: 123qwe
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./volumes/mysql:/var/lib/mysql