name: '[운영환경 배포] frontend'

on:
  workflow_dispatch:
  push:
    branches:
      - production
    paths:
      - apps/frontend/**
      - libs/**

jobs:
  deploy-frontend-production:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-frontend-production
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build
        run: docker build . -t frontend --build-arg APP_NAME=frontend
