name: '[운영환경 배포] backend'

on:
  workflow_dispatch:
  push:
    branches:
      - production
    paths:
      - apps/backend/**
      - libs/**
      - package-lock.json
      - dockerfile

jobs:
  deploy-backend-production:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-backend-production
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build
        run: docker build . -t backend --build-arg APP_NAME=backend
