name: '[개발환경 배포] frontend'

on:
  workflow_dispatch:
  push:
    branches:
      - development
    paths:
      - apps/frontend/**
      - libs/**
      - package-lock.json
      - dockerfile

jobs:
  deploy-frontend-development:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-frontend-development
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build
        run: docker build . -t frontend --build-arg APP_NAME=frontend
