name: '[개발환경 배포] backend'

on:
  workflow_dispatch:
  push:
    branches:
      - development
    paths:
      - apps/backend/**
      - libs/**

jobs:
  deploy-backend-development:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-backend-development
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build
        run: docker build . -t backend --build-arg APP_NAME=backend
